version: '3'

vars:
  USER_NAME: jiro4989
  USER_EMAIL: jiroron666@gmail.com
  GLOBAL_BIN_DIR: /usr/local/bin
  JAVA_HOME: /opt/java/current
  MOUNT_HOME: /mnt/c/Users/jiro4989
  NODE_VERSION: 16.9.1
  CLOJURE_VERSION: 1.10.1.763
  CLOJURE_LSP_VERSION: 2021.02.02-14.02.23
  DIRENV_VERSION: 2.21.3
  MMV_VERSION: 0.1.1
  RIPGREP_VERSION: 12.1.1
  FZF_VERSION: 0.25.1
  SHFMT_VERSION: 3.0.1
  GHQ_VERSION: 1.1.0
  DOCKERCOMPOSE_VERSION: 1.25.4
  GRON_VERSION: 0.6.1
  NEOVIM_VERSION: 0.5.1

env:
  JAVA_HOME: "{{.JAVA_HOME}}"
  SHELL: /bin/bash
  PATH:
    sh: echo "$PATH:$HOME/.nimble/bin:$HOME/.anyenv/bin:{{.JAVA_HOME}}/bin:$HOME/bin:/usr/local/go/bin"

tasks:
  setup:
    desc: "開発環境を構築する"
    deps:
      - install:apt
      - install:docker-compose
      - install:neovim
      - install:shfmt
      - install:fzf
      - install:go
      - install:java
      - install:mmv
      - install:direnv
    cmds:
      - task: copy:netrc
      - task: copy:ssh-config
      - task: install:ghq
      - task: config:git
      - task: config:dotfiles
      - task: config:fish
      - task: config:docker
      - task: config:default-shell
      - task: install:nim
      - task: install:ripgrep
      - task: install:gopls
      - task: install:goimports
      - task: install:anyenv
      - task: install:nodenv
      - task: install:clojure
      - task: install:clojure-lsp
      - task: install:cfn-lint
      - task: install:lein
      - task: install:repos
      - task: install:bash-language-server
      - task: install:gron

  install:apt:
    desc: "aptパッケージをインストールする"
    cmds:
      - sudo add-apt-repository -y ppa:lazygit-team/release
      - sudo add-apt-repository -y ppa:cwchien/gradle
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update -yqq
      - >
        sudo apt-get install -y
          build-essential
          ca-certificates
          ctags
          ctop
          curl
          docker.io
          fish
          git
          gradle
          htop
          lazygit
          npm
          python3
          python3-pip
          shellcheck
          terraform-ls
          tmux
          unzip
          vim
          wget
          xsel
          xvfb
      - sudo add-apt-repository -y ppa:git-core/ppa
      - sudo apt-get install -y git
    status:
      - which fish

  install:docker-compose:
    desc: "docker-composeをインストールする"
    dir: /tmp
    cmds:
      - curl -sL "https://github.com/docker/compose/releases/download/{{.DOCKERCOMPOSE_VERSION}}/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
      - sudo install -m 0755 docker-compose {{.GLOBAL_BIN_DIR}}/docker-compose
    status:
      - test -f {{.GLOBAL_BIN_DIR}}/docker-compose
      - "{{.GLOBAL_BIN_DIR}}/docker-compose version | grep '{{.DOCKERCOMPOSE_VERSION}}'"

  install:neovim:
    desc: "neovimをインストールする"
    dir: /tmp
    cmds:
      - "curl -sSfL https://github.com/neovim/neovim/releases/download/v{{ .NEOVIM_VERSION }}/nvim.appimage > nvim"
      - sudo install -m 0755 nvim {{.GLOBAL_BIN_DIR}}/nvim
    status:
      - test -f {{.GLOBAL_BIN_DIR}}/nvim

  install:ghq:
    desc: "ghqをインストールする"
    deps:
      - install:apt
    dir: /tmp
    cmds:
      - 'curl -sSL https://github.com/x-motemen/ghq/releases/download/v{{.GHQ_VERSION}}/ghq_linux_amd64.zip > ghq_linux_amd64.zip'
      - unzip ghq_linux_amd64.zip
      - sudo install -m 0755 ghq_linux_amd64/ghq {{.GLOBAL_BIN_DIR}}/ghq
    status:
      - test -f {{.GLOBAL_BIN_DIR}}/ghq
      - '{{.GLOBAL_BIN_DIR}}/ghq --version | grep "{{.GHQ_VERSION}}"'

  install:shfmt:
    desc: "shfmtをインストールする"
    dir: /tmp
    cmds:
      - 'curl -sSfL https://github.com/mvdan/sh/releases/download/v{{.SHFMT_VERSION}}/shfmt_v{{.SHFMT_VERSION}}_linux_amd64 > shfmt'
      - sudo install -m 0755 shfmt {{.GLOBAL_BIN_DIR}}/shfmt
    status:
      - test -f {{.GLOBAL_BIN_DIR}}/shfmt
      - '{{.GLOBAL_BIN_DIR}}/shfmt -version | grep "{{.SHFMT_VERSION}}"'

  install:fzf:
    desc: "fzfをインストールする"
    dir: /tmp
    cmds:
      - "wget https://github.com/junegunn/fzf/releases/download/{{.FZF_VERSION}}/fzf-{{.FZF_VERSION}}-linux_amd64.tar.gz"
      - tar xzf fzf-*-linux_amd64.tar.gz
      - sudo install -m 0755 fzf {{.GLOBAL_BIN_DIR}}/fzf
    status:
      - test -f {{.GLOBAL_BIN_DIR}}/fzf
      - '{{.GLOBAL_BIN_DIR}}/fzf --version | grep "{{.FZF_VERSION}}"'

  install:ripgrep:
    desc: "ripgrepをインストールする"
    dir: /tmp
    cmds:
      - "curl -LO https://github.com/BurntSushi/ripgrep/releases/download/{{.RIPGREP_VERSION}}/ripgrep_{{.RIPGREP_VERSION}}_amd64.deb"
      - sudo dpkg -i ./ripgrep_*_amd64.deb
    status:
      - which rg
      - rg --version | grep "{{.RIPGREP_VERSION}}"

  install:go:
    desc: "goをインストールする"
    dir: /usr/local
    cmds:
      - sudo wget https://golang.org/dl/go1.14.6.linux-amd64.tar.gz
      - sudo tar xzf go*.linux-amd64.tar.gz
    status:
      - test -d /usr/local/go

  install:java:
    desc: "javaをインストールする"
    dir: /tmp
    cmds:
      - curl -O https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_linux-x64_bin.tar.gz
      - tar xvf openjdk-14_linux-x64_bin.tar.gz
      - sudo mkdir -p /opt/java
      - sudo mv jdk-14 /opt/java/
      - sudo ln -sfn /opt/java/jdk-14 /opt/java/current
    status:
      - test -e /opt/java/current
      - test -e /opt/java/jdk-14

  config:git:
    desc: "git configを設定する"
    cmds:
      - git config --global user.name {{.USER_NAME}}
      - git config --global user.email {{.USER_EMAIL}}
      - git config --global alias.preq pull-request
      - git config --global alias.see browse
      - git config --global ghq.root ~/src
    status:
      - git config --global --get ghq.root

  install:nim:
    desc: "nimをインストールする"
    dir: /tmp
    cmds:
      - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      - sh init.sh -y > /dev/null 2>&1
      - nimble install -Y inim bump subnet nimjson
    status:
      - test -e $HOME/.nimble/bin/nim
      - test -e $HOME/.nimble/bin/nimble
      - test -e $HOME/.nimble/bin/nimjson

  install:mmv:
    desc: "mmvをインストールする"
    dir: /tmp
    cmds:
      - mkdir -p $HOME/bin
      - "wget https://github.com/itchyny/mmv/releases/download/v0.1.1/mmv_v{{.MMV_VERSION}}_linux_amd64.tar.gz"
      - tar xzf ./mmv*.tar.gz
      - install -m 0755 ./mmv*/mmv $HOME/bin/mmv
    status:
      - test -e $HOME/bin/mmv
      - $HOME/bin/mmv -version | grep "{{.MMV_VERSION}}"

  install:direnv:
    desc: "direnvをインストールする"
    dir: /tmp
    cmds:
      - mkdir -p $HOME/bin
      - "wget https://github.com/direnv/direnv/releases/download/v{{.DIRENV_VERSION}}/direnv.linux-amd64"
      - install -m 0755 ./direnv* $HOME/bin/direnv
    status:
      - test -e $HOME/bin/direnv
      - $HOME/bin/direnv version | grep "{{.DIRENV_VERSION}}"

  install:gopls:
    desc: "goplsをインストールする"
    deps:
      - install:go
    cmds:
      - go get -v -u golang.org/x/tools/gopls
    status:
      - test -e $HOME/go/bin/gopls

  install:bash-language-server:
    desc: "bash-language-serverをインストールする"
    cmds:
      - sudo npm i -g bash-language-server
    status:
      - which bash-language-server

  install:gron:
    desc: "gronをインストールする"
    dir: /tmp
    cmds:
      - wget https://github.com/tomnomnom/gron/releases/download/v{{.GRON_VERSION}}/gron-linux-amd64-{{.GRON_VERSION}}.tgz
      - tar xzf gron-linux-amd64-{{.GRON_VERSION}}.tgz
      - sudo install -m 0755 gron {{.GLOBAL_BIN_DIR}}/gron
    status:
      - which gron

  install:goimports:
    desc: "goimportsをインストールする"
    deps:
      - install:go
    cmds:
      - go get -v -u golang.org/x/tools/cmd/goimports
    status:
      - test -e $HOME/go/bin/goimports

  install:anyenv:
    desc: "anyenvをインストールする"
    cmds:
      - git clone https://github.com/riywo/anyenv ~/.anyenv
      - mkdir -p $(anyenv root)/plugins
      - yes | anyenv install --init
      - git clone https://github.com/znz/anyenv-update.git $(anyenv root)/plugins/anyenv-update
    status:
      - test -e $HOME/.anyenv/bin/anyenv
      - test -e $HOME/.anyenv/plugins/anyenv-update

  install:nodenv:
    desc: "nodenvをインストールする"
    deps:
      - install:anyenv
    cmds:
      - anyenv install nodenv
      - |
        anyenv init - | source
        nodenv install {{.NODE_VERSION}}
        nodenv global {{.NODE_VERSION}}
        node -v
    status:
      - test -e $HOME/.anyenv/envs/nodenv/bin/nodenv
      - test $(nodenv -v | grep {{.NODE_VERSION}} | wc -l) -eq 1

  install:clojure:
    desc: "clojureをインストールする"
    dir: /tmp
    deps:
      - install:java
    vars:
      INSTALL_SCRIPT: 'linux-install-{{.CLOJURE_VERSION}}.sh'
    cmds:
      - "curl -O https://download.clojure.org/install/{{.INSTALL_SCRIPT}}"
      - "chmod +x {{.INSTALL_SCRIPT}}"
      - "sudo ./{{.INSTALL_SCRIPT}}"
    status:
      - test -e /usr/local/bin/clojure
      - /usr/local/bin/clojure -e '(clojure-version)' | grep "$(echo {{.CLOJURE_VERSION}} | sed -E 's/.[0-9]+$//')"

  install:clojure-lsp:
    desc: "clojure-lspをインストールする"
    dir: /tmp
    deps:
      - install:java
    vars:
      INSTALL_SCRIPT: 'linux-install-{{.CLOJURE_VERSION}}.sh'
    cmds:
      - "wget https://github.com/clojure-lsp/clojure-lsp/releases/download/{{.CLOJURE_LSP_VERSION}}/clojure-lsp-native-linux-amd64.zip"
      - unzip clojure-lsp-native-linux-amd64.zip
      - "sudo install -m 0755 ./clojure-lsp {{.GLOBAL_BIN_DIR}}/"
    status:
      - "test -f {{.GLOBAL_BIN_DIR}}/clojure-lsp"

  install:cfn-lint:
    desc: "cfn-lintをインストールする"
    deps:
      - install:apt
    cmds:
      - pip3 install cfn-lint
    status:
      - test -f $HOME/.local/bin/cfn-lint

  install:lein:
    desc: "leinをインストールする"
    dir: /tmp
    deps:
      - install:java
    cmds:
      - mkdir -p $HOME/bin
      - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      - install -m 0755 lein $HOME/bin/lein
      - lein
    status:
      - test -e $HOME/bin/lein

  config:dotfiles:
    desc: "dotfilesをインストールする"
    dir: $HOME
    cmds:
      - git clone https://github.com/jiro4989/dotfiles
      - cd dotfiles && ./setup.sh
    status:
      - test -d $HOME/dotfiles
      - test -e $HOME/.config/fish/config.fish

  config:fish:
    desc: "fishのプラグインを入れる"
    deps:
      - install:apt
      - config:dotfiles
    cmds:
      - curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
      - fish -c "fisher install edc/bass"
      - fish -c "fisher install oh-my-fish/theme-clearance"
      - fish -c "fisher install fisherman/z"
    status:
      - test $(fish -c 'fisher list' | wc -l) -ne 0

  config:docker:
    desc: "dockerの設定をする"
    deps:
      - install:apt
    cmds:
      - sudo usermod -a -G docker {{.USER_NAME}}
    status:
      - test $(groups | grep docker | wc -l) -eq 1

  config:default-shell:
    desc: "デフォルトシェルを変更する"
    deps:
      - install:apt
    cmds:
      - sudo chsh -s $(which tmux) {{.USER_NAME}}
    status:
      - test $(cat /etc/passwd | grep {{.USER_NAME}} | grep tmux | wc -l) -eq 1

  copy:netrc:
    desc: ".netrcをコピー"
    cmds:
      - cp {{.MOUNT_HOME}}/.netrc ~/
    status:
      - test -f ~/.netrc

  copy:ssh-config:
    desc: "ssh configをコピー"
    cmds:
      - install -o {{.USER_NAME}} -g {{.USER_NAME}} -m 0700 -d ~/.ssh
      - cp -r {{.MOUNT_HOME}}/.ssh/config ~/.ssh/
      - cp -r {{.MOUNT_HOME}}/.ssh/conf.d ~/.ssh/
      - chmod 0600 ~/.ssh/conf.d/*
      - chmod 0700 ~/.ssh/conf.d
      - chown -R {{.USER_NAME}}:{{.USER_NAME}} ~/.ssh/conf.d
    status:
      - test -d ~/.ssh
      - test -d ~/.ssh/conf.d
      - test -f ~/.ssh/conf.d/jiro4989
      - test -f ~/.ssh/config

  install:repos:
    desc: "必要なリポジトリをcloneしてくる"
    deps:
      - install:ghq
    vars:
      REPOS: >
        jiro4989/workspace
        jiro4989/sandbox
        jiro4989/setup-nim-action
        jiro4989/websh
        jiro4989/textimg
        jiro4989/faker
        jiro4989/nimjson
        jiro4989/scripts
    cmds:
      - '{{.GLOBAL_BIN_DIR}}/ghq get -P {{.REPOS}}'
    status:
      - |
        for repo in {{.REPOS}}; do
          repo_path=$({{.GLOBAL_BIN_DIR}}/ghq root)/github.com/$repo
          test -d "$repo_path"
        done
