---

- name: Install shells and terminal
  become: true
  pacman:
    name:
      - zsh
      - tmux
      - shellcheck
      - bash-bats
    update_cache: yes
    state: latest
  when: ansible_distribution == "Archlinux"

- name: make my source directory
  file:
    path: "{{ git_dir }}"
    state: directory

- name: git clone dotfiles
  git:
    repo: "https://github.com/jiro4989/dotfiles"
    dest: "{{ git_dir }}/dotfiles"
  ignore_errors: true

- name: bashrc exists
  stat:
    path: "{{ home }}/.bashrc"
  register: bashrc_file

- name: Add source my bashrc
  lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/bash/bashrc
  when: bashrc_file.stat.exists

- name: Create empty zshrc
  file:
    path: "{{ home }}/.zshrc"
    state: touch

- name: zshrc exists
  stat:
    path: "{{ home }}/.zshrc"
  register: zshrc_file

- name: Add source my zshrc
  lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/zsh/zshrc
  when: zshrc_file.stat.exists

- name: Change shell to zsh
  become: true
  shell: "chsh -s /usr/bin/zsh"

- name: Create tmux.conf link
  file:
    src: "{{ git_dir }}/dotfiles/tmux.conf"
    dest:  "{{ home }}/.tmux.conf"
    state: link

