---

- name: make my source directory
  file:
    path: "{{ my_git_repo_root }}"
    state: directory

- name: git clone dotfiles
  git:
    repo: "https://github.com/jiro4989/dotfiles"
    dest: "{{ my_git_repo_root }}/dotfiles"
  ignore_errors: true

- name: bashrc exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
  register: bashrc_file

- name: Add source my bashrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/bash/bashrc
  when: bashrc_file.stat.exists

- name: Create empty zshrc
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: touch

- name: zshrc exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
  register: zshrc_file

- name: Add source my zshrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/zsh/zshrc
  when: zshrc_file.stat.exists

- name: Change shell to zsh
  become: true
  shell: "chsh -s /usr/bin/zsh"

- name: Create tmux.conf link
  file:
    src: "{{ lookup('env', 'HOME') }}/src/github.com/jiro4989/dotfiles/tmux.conf"
    dest:  "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link

