# プラグイン管理・遅延ロード
[[plugins]]
repo = 'Shougo/dein.vim'

# 統一的UI
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_add = '''
nnoremap [denite] <Nop>

" プレフィックスキー
nmap <Leader>u [denite]

nmap <silent> [denite]h :<C-u>Denite file_mru<CR>
nmap <silent> [denite]g :<C-u>Denite grep<CR>
nmap <silent> [denite]t :<C-u>Denite filetype<CR>
nmap <silent> [denite]p :<C-u>Denite file_rec<CR>
nmap <silent> [denite]j :<C-u>Denite line<CR>
nmap <silent> [denite]] :<C-u>DeniteCursorWord grep<CR>
nmap <silent> [denite]y :<C-u>Denite neoyank<CR>
nmap <silent> [denite]r :<C-u>Denite -resume<CR>

" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

# ファイラー
[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
nnoremap <Leader>v :e .<CR>
'''

# 桁揃え
[[plugins]]
repo = 'h1mesuke/vim-alignta'
hook_add = '''
vnoremap gf= :Align=<CR>
vnoremap gf: :Align:<CR>
vnoremap gf, :Align,<CR>
vnoremap gf. :Align.<CR>
vnoremap gf() :Align ( )<CR>
'''

# 括り文字操作
[[plugins]]
repo = 'tpope/vim-surround'

# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'

# コメントアウト
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nmap <Leader>c <Plug>(caw:I:toggle)
vmap <Leader>c <Plug>(caw:I:toggle)
'''

# 折りたたみ時のタイトル表示変更
[[plugins]]
repo = 'LeafCage/foldCC'

# スニペット
[[plugins]]
repo = 'honza/vim-snippets'

# オートコンプリート + Language Server Protocol
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''

" 補完時に文字が消えるのを回避するため
let g:lsp_text_edit_enabled = 0

" Python
if executable('pyls')
  au User lsp_setup call lsp#register_server({
    \ 'name': 'pyls',
    \ 'cmd': {server_info->['pyls']},
    \ 'whitelist': ['python'],
    \ })
endif

" Go
if executable('gopls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls', '-mode', 'stdio']},
        \ 'whitelist': ['go'],
        \ })
    autocmd BufWritePre *.go LspDocumentFormatSync
    autocmd FileType go setlocal omnifunc=lsp#complete
endif

" CSS
if executable('css-languageserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'css-languageserver',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'css-languageserver --stdio']},
        \ 'whitelist': ['css', 'less', 'sass'],
        \ })
endif

" Bash
if executable('bash-language-server')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'bash-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'bash-language-server start']},
        \ 'whitelist': ['sh'],
        \ })
endif

" JavaScript and TypeScript
if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'javascript support using typescript-language-server',
      \ 'cmd': { server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
      \ 'root_uri': { server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))},
      \ 'whitelist': ['javascript', 'javascript.jsx', 'typescript']
      \ })
    autocmd FileType javascript setlocal omnifunc=lsp#complete
    autocmd FileType javascript.jsx setlocal omnifunc=lsp#complete
    autocmd FileType typescript setlocal omnifunc=lsp#complete
endif

" Clojure
if executable('clojure-lsp')
  au User lsp_setup call lsp#register_server({
    \ 'name': 'clojure-lsp',
    \ 'cmd': {server_info->['clojure-lsp']},
    \ 'whitelist': ['clojure'],
    \ })
endif

" Kotlin
if executable(expand('kotlin-language-server'))
    au User lsp_setup call lsp#register_server({
        \ 'name': 'kotlin-language-server',
        \ 'cmd': {server_info->[
        \     &shell,
        \     &shellcmdflag,
        \     expand('kotlin-language-server')
        \ ]},
        \ 'whitelist': ['kotlin']
        \ })
endif

" Java
let s:jdtls_dir = '/opt/jdtls/current'
let s:java_launcher = s:jdtls_dir . '/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar'
if executable('java') && filereadable(expand(s:java_launcher))

    " vim-lsp の設定
    au User lsp_setup call lsp#register_server({
        \ 'name': 'eclipse.jdt.ls',
        \ 'cmd': {server_info->[
        \     'java',
        \     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        \     '-Dosgi.bundles.defaultStartLevel=4',
        \     '-Declipse.product=org.eclipse.jdt.ls.core.product',
        \     '-Dlog.level=ALL',
        \     '-noverify',
        \     '-Dfile.encoding=UTF-8',
        \     '-Xmx1G',
        \     '-jar',
        \     expand(s:java_launcher),
        \     '-configuration',
        \     expand(s:jdtls_dir . '/config_linux'),
        \     '-data',
        \     getcwd()
        \ ]},
        \ 'whitelist': ['java'],
        \ })
endif

let g:lsp_async_completion = 1
nnoremap <silent> gd :LspDefinition<CR>
nnoremap <silent> gp :LspHover<CR>
nnoremap <silent> gr :LspReferences<CR>
nnoremap <silent> gi :LspImplementation<CR>
nnoremap <silent> gs :split \| :LspDefinition <CR>
nnoremap <silent> gv :vsplit \| :LspDefinition <CR>

'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
" TABで補完
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'

# LSPのシンボル・タグビューワ
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction

set statusline+=%{NearestMethodOrFunction()}

" By default vista.vim never run if you don't call it explicitly.
"
" If you want to show the nearest function in your statusline automatically,
" you can add the following line to your vimrc 
autocmd VimEnter * call vista#RunForNearestMethodOrFunction()

let g:vista_sidebar_width = 40
let g:vista_echo_cursor = 0

" デフォルトの情報ソースをctagsにする
let g:vista_default_executive = 'ctags'
" 特定の言語の場合vim-lspを利用した情報ソースを利用するようにする
let g:vista_executive_for = {
    \ 'go': 'vim_lsp',
    \ 'python': 'vim_lsp',
    \ }

" トグル(アウトラインを非表示の場合は表示、表示済みの場合は非表示に)
nnoremap <silent> <Leader>o :<C-u>Vista!!<CR>
'''

# 差分表示を左端に表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 非同期コードチェック
[[plugins]]
repo = 'w0rp/ale'
