---

GOPATH: "{{ lookup('env', 'HOME') }}"
base_dir: /usr/local
go_version: go1.12

download_file: "{{ go_version }}.linux-amd64.tar.gz"
download_url: "https://dl.google.com/go/{{ download_file }}"

src_dir: "{{ base_dir }}/src"
bin_dir: "{{ base_dir }}/bin"
work_dir: "{{ src_dir }}/{{ go_version }}"

archive_file: "{{ work_dir }}/{{ download_file }}"
source_dir: "{{ work_dir }}/go"
