---

- name: Make i3wm config directory
  file:
    path: "{{ home }}/.config/i3"
    state: directory

- name: Make symlink of i3wm config file
  file:
    src: "{{ git_dir }}/dotfiles/i3/config"
    dest: "{{ home }}/.config/i3/config"
    state: link
