---

- git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: user.email
      value: "jiroron666@gmail.com"
    - name: user.name
      value: "jiro4989"
    - name: alias.preq
      value: "pull-request"
    - name: alias.see
      value: "browse"
    - name: alias.co
      value: "checkout"
    - name: alias.fpr
      value: "!f(){ git fetch origin pull/$1/head:$1; git checkout $1; };f"
    - name: commit.template
      value: "~/src/github.com/jiro4989/dotfiles/git/commit.template"
    - name: ghq.root
      value: "~/src"
    - name: pull.ff
      value: "only"
