- hosts: localhost
  connection: local
  vars_files:
    - "vars/env.yml"
  roles:
    - common_deploy
    - nodejs
    - git
    - go
    - docker
    - vim
    - shell
    - i3
    - terminal
    - font
    - vscode
    - nim
