---

- name: Install shells and terminal
  become: true
  pacman:
    name:
      - termite
    update_cache: yes
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Create link of urxvt config file
  file:
    path: "{{ home }}/.config/termite"
    state: directory

- name: Create link of urxvt config file
  file:
    src: "{{ git_dir }}/dotfiles/termite/config"
    dest: "{{ home }}/.config/termite/config"
    state: link
