#!/usr/bin/env zsh

script_dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

# sourceで直接複数指定できないみたいだったのでforループ
for f in "$script_dir"/conf.d/*.zsh; do
  source "$f"
done

source "$script_dir/plugins.zsh"

export HISTFILE=${HOME}/.zsh_history

# メモリに保存される履歴の件数
export HISTSIZE=1000

# 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000

# 重複を記録しない
setopt hist_ignore_dups

# 開始と終了を記録
setopt EXTENDED_HISTORY

setopt prompt_subst #表示毎にPROMPTで設定されている文字列を評価する
