#!/bin/bash

script_dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
lib_dir="$script_dir/../lib/sh"

# キー入力ロックを無効化
stty stop undef

# bash/zsh共通設定
for f in "$lib_dir"/*.sh; do
  source "$f"
done

source "$script_dir/plugins.sh"

function _update_ps1() {
    PS1="$(powerline-shell $?)
\\$ "
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
