#!/bin/bash

script_dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

# 日本語を使用
export LANG=ja_JP.UTF-8

# Java
export JAVA_HOME=/usr/lib/jvm/java-10-openjdk
export PATH=$JAVA_HOME/bin:$PATH

# Go
export GOPATH=$HOME
export PATH=$PATH:/usr/lib/go-1.10/bin

# 追加したコマンド系
export PATH=$PATH:$HOME/bin

# Rust
export PATH=$PATH:$HOME/.cargo/bin

# nim
export PATH=/home/jiro/.nimble/bin:$PATH

export BROWSER=chromium-browser

# キー入力ロックを無効化
stty stop undef

export SDKMAN_DIR="/home/jiro/.sdkman"
[[ -s "/home/jiro/.sdkman/bin/sdkman-init.sh" ]] && source "/home/jiro/.sdkman/bin/sdkman-init.sh"

# 画面ロック
alias lock='gnome-screensaver-command -l'
# git log one line
alias glog='git log --graph --all --format="%x09%C(cyan bold)%an%Creset%x09%C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s"'
alias ll='ls -la'
alias llh='ls -lah'
alias gomydir="cd $GOPATH/src/github.com/jiro4989"
alias open="xdg-open"
alias o="open"
alias e="eog"
alias ld="find . -maxdepth 1 -type d"
alias d="docker"
alias dc="docker-compose"
alias dclean="docker ps -qa | xargs docker stop | xargs docker rm -f"
alias diclean="docker images -qa | xargs docker rmi"
alias dvprune="docker volume prune -f"
alias change_terminal="sudo update-alternatives --config x-terminal-emulator"
alias histclip="fc -ln | tail -n 1 | sed -r 's@^\s+@@g' | gocopy"

# burnout はdockerを全部キレイにする
burnout() {
  dclean
  diclean
  dvprune
}

# din は起動済みコンテナに接続する
din() {
  d exec -it $@ bash
}

# ghq管理のディレクトリ配下からリポジトリを検索し、cwdを移動する
peco_src() {
  local selected_dir
  selected_dir=$(ghq list --full-path | peco)
  if [[ "$selected_dir" != "" ]]; then
    cd "$selected_dir"
  fi
}

export EDITOR=vim
export BROWSER=chromium-browser
export TERMINAL=terminator

export CGO_CXXFLAGS_ALLOW=".*" 
export CGO_LDFLAGS_ALLOW=".*" 
export CGO_CFLAGS_ALLOW=".*" 

#export QT_DIR="$HOME/Qt"
#export QT_VERSION="5.11.1"

HISTTIMEFORMAT='%Y-%m-%dT%T%z '

source "$script_dir/plugins.sh"

# プロンプトの表示を変更
export PS1='\[\033[01;33m\][\t]\[\033[00m\] \[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[\033[01;35m\]$(__git_ps1 "(%s)")\[\033[00m\]\$ '

