---

name: test

"on":
  push:
    branches:
      - master
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy script
        run: ./setup.sh
