name: test

on: push

jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        service:
          - manjaro
          - manjaro_curl
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - run: |
        :
        # echo "BRANCH=${{ steps.extract_branch.outputs.branch }}" > .env
        # docker-compose run "${{ matrix.service }}"
